# Generated by Django 6.0.3 on 2026-03-13 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_homepage_body'),
        ('wagtailimages', '0027_image_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='button_text',
            field=models.CharField(default='About EmpowerME', max_length=50),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image'),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='quote_author',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
