# Generated by Django 6.0.3 on 2026-03-13 23:21

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_remove_homepage_body_homepage_button_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='courses_section',
            field=wagtail.fields.StreamField([('course_circle', 2)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': 'e.g. #f7b7a3'}), 2: ('wagtail.blocks.StructBlock', [[('title', 0), ('background_color', 1)]], {})}, null=True),
        ),
    ]
